#!/usr/bin/env python3
"""SYNTHETIC data generator -- NOT a measurement.

Produces data/sample_synthetic.csv with the same schema as a real sweep so the
plotting pipeline can be exercised without a GPU. Every number comes from a toy
Little's-Law model below, not from hardware. Do not cite it.
"""
import os

import numpy as np

SPEC = 3352.0          # GB/s  -- toy HBM3e-class peak
BW_MAX = 0.82 * SPEC   # achievable plateau
LAT_NS = 480.0         # toy memory latency
NAME = "SYNTHETIC-HBM3e"
ITERS = 512
FOOTPRINT = 2147483648

HEADER = (
    "gpu_name,vec_bytes,stride,resident_warps,ilp,footprint_bytes,iters,"
    "bytes_moved,time_ms,achieved_gbps,spec_gbps,pct_of_spec,bytes_in_flight"
)

rng = np.random.default_rng(0)
rows = []


def emit(vec: int, stride: int, warps: int, ilp: int) -> None:
    threads = ((warps * 32 + 255) // 256) * 256
    bif = threads * ilp * vec
    c_knee = BW_MAX * LAT_NS
    bw = BW_MAX * bif / (bif + c_knee)                       # Little's Law + saturation
    bw *= (1.0 / (1.0 + 0.06 * (stride - 1))) if stride > 1 else 1.0  # stride efficiency
    bw *= {4: 0.80, 8: 0.92, 16: 1.0}[vec]                   # narrow-access penalty
    bw *= rng.normal(1.0, 0.01)                              # run-to-run noise
    bytes_moved = ITERS * threads * ilp * vec
    t_ms = bytes_moved / (bw * 1e9) * 1e3
    rows.append(
        f'"{NAME}",{vec},{stride},{threads // 32},{ilp},{FOOTPRINT},{ITERS},'
        f"{bytes_moved:.0f},{t_ms:.5f},{bw:.3f},{SPEC:.3f},"
        f"{100 * bw / SPEC:.2f},{bif:.0f}"
    )


WARP_LADDER = [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048]

for st in [1, 2, 4, 8, 16, 32, 64, 128, 256]:
    emit(16, st, 2048, 4)
for vec in [4, 8, 16]:
    emit(vec, 1, 2048, 4)
for w in WARP_LADDER:
    for ilp in [1, 2, 4, 8]:
        emit(16, 1, w, ilp)

os.makedirs("data", exist_ok=True)
with open("data/sample_synthetic.csv", "w", encoding="utf-8") as f:
    f.write("# SYNTHETIC -- generated by scripts/synthesize_sample.py, not a measurement\n")
    f.write(HEADER + "\n")
    f.write("\n".join(rows) + "\n")

print("wrote data/sample_synthetic.csv  (SYNTHETIC -- toy model, not hardware)")
